# Generated by Django 4.1.2 on 2022-11-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0005_tag_alter_category_options_joke_category_joke_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
