# Generated by Django 4.1.2 on 2022-11-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_joke_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='user',
        ),
    ]
